using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Unity.Collections;

namespace AncientMonkey
{
    public static class Settings
    {/*
        public static Dictionary<string, object> settingsValue = new Dictionary<string, object>()
        {
            {"SandboxMode", false},
            {"Cheats", false},
            {"NewWeaponStartingCost", 325f},
            {"IncrementalNewWeaponStartingCost", 250f},
            {"IncrementalNewWeaponCostMultiplier", 1.06f},
            {"StrongerWeaponStartingCost", 500f},
            {"IncrementalStrongerWeaponStartingCost", 500f},
            {"IncrementalStrongerWeaponCostMultiplier", 1.06f},
            {"NewAbilityStartingCost", 7500f},
            {"IncrementalNewAbilityStartingCost", 1000f},
            {"IncrementalNewAbilityCostMultiplier", 1f},
            {"ExtraLuckStartingCost", 700f},
            {"ExtraLuckCostIncreaseMultiplier", 1.35f},
            {"ExtraLuckUpgradeCount", 20},
            {"ExtraAbilitySlotStartingCost", 100000f},
            {"ExtraAbilitySlotIncreaseMultiplier", 1.15f},
            {"ExtraAbilitySlotUpgradeCount", 1},
            {"ExtraWeaponSlotStartingCost", 50000f},
            {"ExtraWeaponSlotIncreaseMultiplier", 1.15f},
            {"ExtraWeaponSlotUpgradeCount", 1},
            {"ExtraStrongerSlotStartingCost", 75000f},
            {"ExtraStrongerSlotIncreaseMultiplier", 1.15f},
            {"ExtraStrongerSlotUpgradeCount", 1},
            {"NewWeaponStartingSlot", 3},
            {"NewAbilityStartingSlot", 1},
            {"StrongerWeaponStartingSlot", 3},
            {"Upgrade1Enabled", true},
            {"Upgrade1Cost", 125000f},
            {"NewWeaponStartingCost1", 450f},
            {"IncrementalNewWeaponStartingCost1", 350f},
            {"IncrementalNewWeaponCostMultiplier1", 1.06f},
            {"StrongerWeaponStartingCost1", 950f},
            {"IncrementalStrongerWeaponStartingCost1", 750f},
            {"IncrementalStrongerWeaponCostMultiplier1", 1.06f},
            {"NewAbilityStartingCost1", 6000f},
            {"IncrementalNewAbilityStartingCost1", 750f},
            {"IncrementalNewAbilityCostMultiplier1", 1f},
            {"NewWeaponSlotBonus1", 1},
            {"StrongerWeaponSlotBonus1", 1},
            {"NewAbilitySlotBonus1", 1},

            {"BaseRareChance", 7},
            {"BaseEpicChance", 0},
            {"BaseLegendaryChance", 0},
            {"BaseExoticChance", 0},
            {"BaseRareChanceUntilEpicChance", 14},
            {"BaseEpicChanceUntilLegendaryChance", 12},
            {"BaseLegendaryChanceUntilExoticChance", 9},
            {"BaseRareChanceDecrease", 5f},
            {"BaseEpicChanceDecrease", 1.45f},
            {"BaseLegendaryChanceDecrease", 0.85f},
            {"BaseExoticChanceDecrease", 0.50f},

            {"Upgrade1EpicChance", 25},
            {"Upgrade1LegendaryChance", 2},
            {"Upgrade1ExoticChance", 0},
            {"Upgrade1GodlyChance", 0},
            {"Upgrade1EpicChanceUntilLegendaryChance", 12},
            {"Upgrade1LegendaryChanceUntilExoticChance", 9},
            {"Upgrade1ExoticChanceUntilGodlyChance", 9},
            {"Upgrade1EpicChanceDecrease", 1.45f},
            {"Upgrade1LegendaryChanceDecrease", 0.85f},
            {"Upgrade1ExoticChanceDecrease", 0.50f},
            {"Upgrade1GodlyChanceDecrease", 0.30f},
        };
        public static Dictionary<string, object> baseValue = new Dictionary<string, object>()
        {
            {"Cheats", false},
            {"SandboxMode", false},
            {"NewWeaponStartingCost", 325f},
            {"IncrementalNewWeaponStartingCost", 250f},
            {"IncrementalNewWeaponCostMultiplier", 1.06f},
            {"StrongerWeaponStartingCost", 500f},
            {"IncrementalStrongerWeaponStartingCost", 500f},
            {"IncrementalStrongerWeaponCostMultiplier", 1.06f},
            {"NewAbilityStartingCost", 7500f},
            {"IncrementalNewAbilityStartingCost", 1000f},
            {"IncrementalNewAbilityCostMultiplier", 1f},
            {"ExtraLuckStartingCost", 700f},
            {"ExtraLuckUpgradeCount", 20},
            {"ExtraAbilitySlotStartingCost", 100000f},
            {"ExtraAbilitySlotIncreaseMultiplier", 1.15f},
            {"ExtraAbilitySlotUpgradeCount", 1},
            {"ExtraWeaponSlotStartingCost", 50000f},
            {"ExtraWeaponSlotIncreaseMultiplier", 1.15f},
            {"ExtraWeaponSlotUpgradeCount", 1},
            {"ExtraStrongerSlotStartingCost", 75000f},
            {"ExtraStrongerSlotIncreaseMultiplier", 1.15f},
            {"ExtraStrongerSlotUpgradeCount", 1},
            {"NewWeaponStartingSlot", 3},
            {"NewAbilityStartingSlot", 1},
            {"StrongerWeaponStartingSlot", 3},
            {"Upgrade1Enabled", true},
            {"Upgrade1Cost", 125000f},
            {"NewWeaponStartingCost1", 450f},
            {"IncrementalNewWeaponStartingCost1", 350f},
            {"IncrementalNewWeaponCostMultiplier1", 1.06f},
            {"StrongerWeaponStartingCost1", 950f},
            {"IncrementalStrongerWeaponStartingCost1", 750f},
            {"IncrementalStrongerWeaponCostMultiplier1", 1.06f},
            {"NewAbilityStartingCost1", 6000f},
            {"IncrementalNewAbilityStartingCost1", 750f},
            {"IncrementalNewAbilityCostMultiplier1", 1f},
            {"NewWeaponSlotBonus1", 1},
            {"StrongerWeaponSlotBonus1", 1},
            {"NewAbilitySlotBonus1", 1},

            {"BaseRareChance", 7},
            {"BaseEpicChance", 0},
            {"BaseLegendaryChance", 0},
            {"BaseExoticChance", 0},
            {"BaseRareChanceUntilEpicChance", 14f},
            {"BaseEpicChanceUntilLegendaryChance", 12f},
            {"BaseLegendaryChanceUntilExoticChance", 9f},
            {"BaseRareChanceDecrease", 5f},
            {"BaseEpicChanceDecrease", 1.45f},
            {"BaseLegendaryChanceDecrease", 0.85f},
            {"BaseExoticChanceDecrease", 0.50f},

            {"Upgrade1EpicChance", 25},
            {"Upgrade1LegendaryChance", 2},
            {"Upgrade1ExoticChance", 0},
            {"Upgrade1GodlyChance", 0},
            {"Upgrade1EpicChanceUntilLegendaryChance", 12},
            {"Upgrade1LegendaryChanceUntilExoticChance", 9},
            {"Upgrade1ExoticChanceUntilGodlyChance", 9},
            {"Upgrade1EpicChanceDecrease", 1.45f},
            {"Upgrade1LegendaryChanceDecrease", 0.85f},
            {"Upgrade1ExoticChanceDecrease", 0.50f},
            {"Upgrade1GodlyChanceDecrease", 0.30f},
        };*/
    }
    
}
